#!make
-include .env
.PHONY: clients
.DEFAULT_GOAL := clients

# Re-create autogenerated client code from OpenAPI spec
# ap-explanation's spec is vendored (openapi/ap_explanation.json) so `make clients`
# works offline and doesn't depend on which image is running. Refresh it with:
#   curl -s http://ap-explanation:5000/openapi.json > openapi/ap_explanation.json
AP_EXPLANATION_SPEC ?= openapi/ap_explanation.json

clients:
	rm -rf generated
	echo "Generating clients from OpenAPI specs..."
	echo "AP_EXPLANATION_SPEC=${AP_EXPLANATION_SPEC}"
	kiota generate --clear-cache --ll Debug -l python -d ${AP_EXPLANATION_SPEC} -o generated/ap_explanation -c ApExplanationClient
